blank_issues_enabled: true
contact_links:
  - name: A security problem
    url: https://github.com/sc0rebreaker/dota-translator/security/advisories/new
    about: Please report it privately, not as a public issue.
